---
title: "Syllabus"
author: "Peter Gilles"
format: html
editor: visual
bibliography: references.bib
project:
  type: website
  output-dir: docs
---

# Language Analytics in R

Seminar in the Doctoral School HSS at the University of Luxembourg \| Summer semester 2026

Initial steps:

-   install R

-   install RStudio

-   install these packages in RStudio: tidyverse, languageR, tidytext, quanteda, quanteda.textmodels, quanteda.textplots, quanteda.textstats, quanteda.tidy, gutenbergr

## Syllabus

-   **1 April**

-   **15 April**

-   **6 May**

-   **20 May**

-   **27 May**

1.  Introduction:
    1.  Examples from own research
    2.  First steps in Rstudio, packages and basic constructs (workflow, variables, scripting in Rmarkdown; writing good code)
    3.  Work with text data and corpora (data import etc.)
    4.  Hands-on exercises on toy data
2.  Data wrangling
    1.  tidyverse
3.  Corpus analysis with tidytext and quanteda
4.  Visualisation and basic statistics with ggplot2
5.  Work on own projects

## Resources and recommended reading

[@levshina2015]

[@schneider2024]

[@winter2020] (<https://appliedstatisticsforlinguists.org/bwinter_stats_proofs.pdf>)

[R for Data Science (2e)](https://r4ds.hadley.nz/)

<https://www.tidytextmining.com/>

<https://eleanorchodroff.com/r-for-linguists/>

<https://jofrhwld.github.io/AandS500_2023/>

<https://jofrhwld.github.io/2023_Lin611/>

<https://jofrhwld.github.io/teaching/courses/2017_lsa/>

<https://alvinntnu.github.io/NTNU_ENC2036_LECTURES/>

## R cheatsheets

<https://posit.co/resources/cheatsheets/>

<https://cran.r-project.org/doc/contrib/Short-refcard.pdf>

## Stilometrics

<https://computationalstylistics.github.io/>

## AI tools

[querychat](https://posit-dev.github.io/querychat/r/index.html)
